version: "3.3"
services:
  mp:
    image: "poo"
    ports:
      - "80:80"
  myred:
    image: "redis"
    ports:
      -  "6000:6379"
    volumes:
      -  data_vol:/app
volumes:
  data_vol:
    driver: local