version: "3.3"
services:
  mp:
    image: "poo"
    ports:
      - "80:80"
  myred:
    image: "redis"
    ports:
      -  "6000:6379"
    volumes:
      -  data_vol:/data
      - /home/mohammadi/a/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  data_vol:
